Dựa trên thể thức của MSI 2026, khả năng cao sẽ có 2 đội LCK và 2 đội LPL trong Bracket Stage -> meta LCK/LPL sẽ có ảnh hưởng lớn hơn. Vì vậy, người viết sẽ sử dụng dữ liệu của các giải đấu sau: 
- LCK 2026 Split 3-4
- LCK 2026 Season Play-In
- LCK 2026 Season Playoffs
- LPL 2026 Split 3
- LPL 2026 Split Grand Finals

Ngoài ra còn sử dụng dữ liệu của các giải đấu quốc tế tiền CKTG:
- Demacia Cup Global Invitational 2026 (aka cúp C2)
- Worlds Star Challengers Invitational 2026 (aka CKTG tier 2)

Dữ liệu được tải về từ Oracle's Elixir.

# Tướng

In [3]:
import pandas as pd
import numpy as np

lck_playoffs_champ = pd.read_csv("Worlds 2026 data\\LCK 2026 Season Playoffs - Champion Stats - OraclesElixir.csv")
lck_playin_champ = pd.read_csv("Worlds 2026 data\\LCK 2026 Season Play-In - Champion Stats - OraclesElixir.csv")
lck_champ = pd.read_csv("Worlds 2026 data\\LCK 2026 Rounds 3-4 - Champion Stats - OraclesElixir.csv")
lpl_playoffs_champ = pd.read_csv("Worlds 2026 data\\LPL 2026 Grand Finals - Champion Stats - OraclesElixir.csv")
lpl_champ = pd.read_csv("Worlds 2026 data\\LPL 2026 Split 3 - Champion Stats - OraclesElixir.csv")
dcgi_champ = pd.read_csv("Worlds 2026 data\\Demacia Cup Global Invitational 2026 - Champion Stats - OraclesElixir.csv")
wsci_champ = pd.read_csv("Worlds 2026 data\\World Star Challengers Invitational 2026 - Champion Stats - OraclesElixir.csv")

In [4]:
# Tiền xử lý dữ liệu để tính toán các chỉ số cần thiết
lck_playoffs_number_of_games = 41
lck_playin_number_of_games = 14
lck_number_of_games = 99
lpl_playoffs_number_of_games = 55
lpl_number_of_games = 167
dcgi_number_of_games = 67 # six seven
wsci_number_of_games = 76 # seven six

def convert_percentage_to_float(value):
    if isinstance(value, object) and str(value).endswith('%'):
        return float(str(value).strip('%')) / 100
    return value

lck_playoffs_champ['B%'] = lck_playoffs_champ['B%'].apply(convert_percentage_to_float)
lck_playin_champ['B%'] = lck_playin_champ['B%'].apply(convert_percentage_to_float)
lck_champ['B%'] = lck_champ['B%'].apply(convert_percentage_to_float)
lpl_playoffs_champ['B%'] = lpl_playoffs_champ['B%'].apply(convert_percentage_to_float)
lpl_champ['B%'] = lpl_champ['B%'].apply(convert_percentage_to_float)
dcgi_champ['B%'] = dcgi_champ['B%'].apply(convert_percentage_to_float)
wsci_champ['B%'] = wsci_champ['B%'].apply(convert_percentage_to_float)

lck_playoffs_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
lck_playin_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
lck_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
lpl_playoffs_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
lpl_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
dcgi_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
wsci_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)

lck_playoffs_champ['Games Banned'] = lck_playoffs_champ['Ban Rate'] * lck_playoffs_number_of_games
lck_playoffs_champ['Games Banned'] = lck_playoffs_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
lck_playin_champ['Games Banned'] = lck_playin_champ['Ban Rate'] * lck_playin_number_of_games
lck_playin_champ['Games Banned'] = lck_playin_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
lck_champ['Games Banned'] = lck_champ['Ban Rate'] * lck_number_of_games
lck_champ['Games Banned'] = lck_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
lpl_playoffs_champ['Games Banned'] = lpl_playoffs_champ['Ban Rate'] * lpl_playoffs_number_of_games
lpl_playoffs_champ['Games Banned'] = lpl_playoffs_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
lpl_champ['Games Banned'] = lpl_champ['Ban Rate'] * lpl_number_of_games
lpl_champ['Games Banned'] = lpl_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
dcgi_champ['Games Banned'] = dcgi_champ['Ban Rate'] * dcgi_number_of_games
dcgi_champ['Games Banned'] = dcgi_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
wsci_champ['Games Banned'] = wsci_champ['Ban Rate'] * wsci_number_of_games
wsci_champ['Games Banned'] = wsci_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)

In [5]:
champ = pd.concat([lck_playoffs_champ, lck_playin_champ, lck_champ, lpl_playoffs_champ, lpl_champ, dcgi_champ, wsci_champ], ignore_index=True)
champ

,Champion,Pos,GP,P%,Ban Rate,P+B%,W%,CTR%,K,D,...,XPD10,CSD10,CSPM,CS%P15,DPM,DMG%,GOLD%,WPM,WCPM,Games Banned
0,Aatrox,Jungle,1,2.4%,0.000,7.3%,100%,100%,7,2,...,-239,-3,7.2,19.8%,682,24.3%,20.6%,0.32,0.16,0
1,Aatrox,Top,2,4.9%,0.000,7.3%,50%,100%,3,5,...,-84,-4,9.1,24.7%,595,23.7%,20.1%,0.43,0.16,0
2,Ahri,Middle,7,17.1%,0.098,26.8%,43%,57%,23,17,...,157,-2.6,9.4,25.5%,645,25.7%,21.9%,0.28,0.31,4
3,Akali,Middle,7,17.1%,0.122,29.3%,57%,43%,39,19,...,-248,0.9,9.3,24.6%,586,26.2%,23.7%,0.31,0.28,5
4,Alistar,Support,5,12.2%,0.049,17.1%,40%,60%,3,17,...,-289,-3.2,0.9,1.6%,111,4.4%,9.4%,2.3,0.3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761,Yuumi,Support,3,4.1%,0.027,6.8%,33%,100%,3,3,...,-31,-7.7,0.5,0.4%,219,9.7%,11.2%,1.78,0.03,2
762,Zaahen,Jungle,2,2.7%,0.014,8.1%,50%,100%,10,8,...,-141,-1.5,7.3,20.7%,536,17.5%,21.0%,0.22,0.42,1
763,Zaahen,Top,3,4.1%,0.014,8.1%,0%,100%,2,10,...,87,-10,7.8,24.3%,565,21.7%,19.6%,0.37,0.16,1
764,Zeri,ADC,3,4.1%,0.014,5.4%,33%,100%,19,7,...,-313,-1.7,11,36.4%,590,27.7%,31.7%,0.36,0.7,1
765,Ziggs,ADC,1,1.4%,0.014,2.7%,100%,100%,2,4,...,103,-6,8.9,33.4%,968,26.7%,24.6%,0.64,0.24,1

### Làm sạch và tiền xử lý dữ liệu

In [6]:
champ[['W%', 'P%']] = champ[['W%', 'P%']].applymap(convert_percentage_to_float)
champ.rename(columns={'W%': 'Win Rate', 'P%': 'Pick Rate'}, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26124\955472751.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  champ[['W%', 'P%']] = champ[['W%', 'P%']].applymap(convert_percentage_to_float)

In [7]:
champ['Game Win'] = champ['GP'] * champ['Win Rate']
champ['Game Win'] = champ['Game Win'].apply(lambda x: round(x) if x != '' else 0)
champ

,Champion,Pos,GP,Pick Rate,Ban Rate,P+B%,Win Rate,CTR%,K,D,...,CSD10,CSPM,CS%P15,DPM,DMG%,GOLD%,WPM,WCPM,Games Banned,Game Win
0,Aatrox,Jungle,1,0.024,0.000,7.3%,1.0,100%,7,2,...,-3,7.2,19.8%,682,24.3%,20.6%,0.32,0.16,0,1
1,Aatrox,Top,2,0.049,0.000,7.3%,0.5,100%,3,5,...,-4,9.1,24.7%,595,23.7%,20.1%,0.43,0.16,0,1
2,Ahri,Middle,7,0.171,0.098,26.8%,0.43,57%,23,17,...,-2.6,9.4,25.5%,645,25.7%,21.9%,0.28,0.31,4,3
3,Akali,Middle,7,0.171,0.122,29.3%,0.57,43%,39,19,...,0.9,9.3,24.6%,586,26.2%,23.7%,0.31,0.28,5,4
4,Alistar,Support,5,0.122,0.049,17.1%,0.4,60%,3,17,...,-3.2,0.9,1.6%,111,4.4%,9.4%,2.3,0.3,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761,Yuumi,Support,3,0.041,0.027,6.8%,0.33,100%,3,3,...,-7.7,0.5,0.4%,219,9.7%,11.2%,1.78,0.03,2,1
762,Zaahen,Jungle,2,0.027,0.014,8.1%,0.5,100%,10,8,...,-1.5,7.3,20.7%,536,17.5%,21.0%,0.22,0.42,1,1
763,Zaahen,Top,3,0.041,0.014,8.1%,0.0,100%,2,10,...,-10,7.8,24.3%,565,21.7%,19.6%,0.37,0.16,1,0
764,Zeri,ADC,3,0.041,0.014,5.4%,0.33,100%,19,7,...,-1.7,11,36.4%,590,27.7%,31.7%,0.36,0.7,1,1
765,Ziggs,ADC,1,0.014,0.014,2.7%,1.0,100%,2,4,...,-6,8.9,33.4%,968,26.7%,24.6%,0.64,0.24,1,1

In [12]:
# pick/ban presence = games played + games banned
champ['Presence'] = champ['GP'] + champ['Games Banned']
champ

,Champion,Pos,GP,Pick Rate,Ban Rate,P+B%,Win Rate,CTR%,K,D,...,CSPM,CS%P15,DPM,DMG%,GOLD%,WPM,WCPM,Games Banned,Game Win,Presence
0,Aatrox,Jungle,1,0.024,0.000,7.3%,1.0,100%,7,2,...,7.2,19.8%,682,24.3%,20.6%,0.32,0.16,0,1,1
1,Aatrox,Top,2,0.049,0.000,7.3%,0.5,100%,3,5,...,9.1,24.7%,595,23.7%,20.1%,0.43,0.16,0,1,2
2,Ahri,Middle,7,0.171,0.098,26.8%,0.43,57%,23,17,...,9.4,25.5%,645,25.7%,21.9%,0.28,0.31,4,3,11
3,Akali,Middle,7,0.171,0.122,29.3%,0.57,43%,39,19,...,9.3,24.6%,586,26.2%,23.7%,0.31,0.28,5,4,12
4,Alistar,Support,5,0.122,0.049,17.1%,0.4,60%,3,17,...,0.9,1.6%,111,4.4%,9.4%,2.3,0.3,2,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761,Yuumi,Support,3,0.041,0.027,6.8%,0.33,100%,3,3,...,0.5,0.4%,219,9.7%,11.2%,1.78,0.03,2,1,5
762,Zaahen,Jungle,2,0.027,0.014,8.1%,0.5,100%,10,8,...,7.3,20.7%,536,17.5%,21.0%,0.22,0.42,1,1,3
763,Zaahen,Top,3,0.041,0.014,8.1%,0.0,100%,2,10,...,7.8,24.3%,565,21.7%,19.6%,0.37,0.16,1,0,4
764,Zeri,ADC,3,0.041,0.014,5.4%,0.33,100%,19,7,...,11,36.4%,590,27.7%,31.7%,0.36,0.7,1,1,4
765,Ziggs,ADC,1,0.014,0.014,2.7%,1.0,100%,2,4,...,8.9,33.4%,968,26.7%,24.6%,0.64,0.24,1,1,2

In [18]:
champ['K'] = champ['K'].apply(lambda x: int(x) if x != '-' else 0)
champ['D'] = champ['D'].apply(lambda x: int(x) if x != '-' else 0)

### Vị tướng nào sẽ được cấm/chọn nhiều nhất?

In [13]:
champ[['Champion','Presence']].groupby('Champion')['Presence'].sum().sort_values(ascending=False).head(15)

Champion
Poppy         580
Cassiopeia    566
Orianna       463
Vi            365
Nocturne      355
Camille       324
Syndra        324
Jayce         306
Akali         301
Lucian        294
Ezreal        284
Olaf          280
Lee Sin       259
Jarvan IV     257
Rumble        247
Name: Presence, dtype: int64

### Vị tướng nào sẽ có tỉ lệ thắng cao nhất? (được sử dụng trong tối thiểu 5 trận)

In [14]:
champ_above_5_games = champ.groupby('Champion')['GP'].sum().sort_values()
champ_above_5_games_list = champ_above_5_games[champ_above_5_games >= 5].index.tolist()

In [15]:
total_games_per_champ = champ[champ['Champion'].isin(champ_above_5_games_list)].where(champ['GP'] > 0).groupby('Champion').agg({'GP': 'sum', 'Game Win': 'sum'})
total_games_per_champ['Win Rate'] = total_games_per_champ['Game Win'] / total_games_per_champ['GP']
total_games_per_champ.sort_values(by='Win Rate', ascending=False)

                GP  Game Win  Win Rate
Champion
Nidalee        9.0       7.0  0.777778
Cassiopeia    78.0      54.0  0.692308
Blitzcrank     6.0       4.0  0.666667
Gwen          12.0       8.0  0.666667
Miss Fortune  20.0      13.0  0.650000
...            ...       ...       ...
Mel           13.0       4.0  0.307692
Zaahen        20.0       6.0  0.300000
Gragas         7.0       2.0  0.285714
Lissandra     12.0       3.0  0.250000
Hwei           6.0       1.0  0.166667

[97 rows x 3 columns]

Người viết bỏ qua Nidalee do số lượng trận đấu quá ít -> chọn Cassiopeia cho mục này.

### Vị tướng nào sẽ có số mạng nằm xuống trung bình mỗi ván đấu cao nhất? (được sử dụng trong tối thiểu 5 trận))

In [25]:
avg_death_per_champ = champ[champ['Champion'].isin(champ_above_5_games_list)].where(champ['GP'] > 0).groupby('Champion').agg({'GP': 'sum', 'D': 'sum'})
avg_death_per_champ['Avg Death'] = avg_death_per_champ['D'] / avg_death_per_champ['GP']

In [24]:
avg_death_per_champ.sort_values(by='Avg Death', ascending=False)

             GP      D  Avg Death
Champion
Pyke        6.0   36.0   6.000000
Nautilus   88.0  391.0   4.443182
Leona      27.0  119.0   4.407407
Camille    78.0  343.0   4.397436
Shyvana    10.0   41.0   4.100000
...         ...    ...        ...
LeBlanc    10.0   22.0   2.200000
Milio     106.0  233.0   2.198113
Nidalee     9.0   18.0   2.000000
Sejuani     7.0   13.0   1.857143
Yuumi      14.0   22.0   1.571429

[97 rows x 3 columns]

Người viết bỏ qua Pyke do số lượng trận đấu quá ít -> chọn Nautilus cho mục này.

# Tuyển thủ

In [29]:
lck_playoffs_player = pd.read_csv("Worlds 2026 data\\LCK 2026 Season Playoffs - Player Stats - OraclesElixir.csv")
lck_playin_player = pd.read_csv("Worlds 2026 data\\LCK 2026 Season Play-In - Player Stats - OraclesElixir.csv")
lck_player = pd.read_csv("Worlds 2026 data\\LCK 2026 Rounds 3-4 - Player Stats - OraclesElixir.csv")
lpl_playoffs_player = pd.read_csv("Worlds 2026 data\\LPL 2026 Grand Finals - Player Stats - OraclesElixir.csv")
lpl_player = pd.read_csv("Worlds 2026 data\\LPL 2026 Split 3 - Player Stats - OraclesElixir.csv")

worlds_team = ['T1', 'Hanwha Life Esports', 'Dplus Kia', 'Gen.G', 'Top Esports', 'Bilibili Gaming', 'Invictus Gaming', "Anyone's Legend"]

player = pd.concat([lck_playoffs_player, lpl_playoffs_player, lck_playin_player, lck_player, lpl_player], ignore_index=True)

In [30]:
player

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,DPM,DMG%,D%P15,TDPG,EGPM,GOLD%,STL,WPM,CWPM,WCPM
0,Bdd,KT Rolster,Middle,10,40%,40%,29,28,51,2.9,...,471,22.3%,21.8%,5497.0,276,22.6%,0.0,0.38,0.15,0.24
1,Canyon,Gen.G,Jungle,11,82%,36%,35,25,106,5.6,...,395,15.0%,16.4%,2292.0,277,19.3%,2.0,0.48,0.36,0.47
2,Career,Dplus Kia,Support,16,44%,50%,11,46,162,3.8,...,197,8.0%,5.9%,1218.0,134,10.4%,0.0,1.95,0.75,0.47
3,Chovy,Gen.G,Middle,11,82%,45%,54,18,77,7.3,...,637,23.8%,23.7%,10648.0,332,23.0%,0.0,0.42,0.11,0.39
4,Clear,BNK FEARX,Top,10,40%,60%,20,27,45,2.4,...,554,21.7%,21.3%,8134.0,259,20.5%,0.0,0.39,0.12,0.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,Ycx,LNG Esports,Support,8,25%,29%,5,22,62,3.0,...,181,8.0%,5.4%,1050.0,125,10.3%,NaN,1.95,0.62,0.42
223,Zdz,EDward Gaming,Top,31,23%,57%,81,136,126,1.5,...,573,22.6%,21.0%,5184.0,250,20.8%,NaN,0.48,0.23,0.21
224,Zhuo,Top Esports,Support,31,58%,60%,27,104,349,3.6,...,196,6.7%,6.0%,898.0,138,10.6%,NaN,2.03,0.50,0.46
225,Zika,Weibo Gaming,Top,16,44%,63%,37,44,67,2.4,...,568,21.7%,21.9%,7140.0,252,20.8%,NaN,0.42,0.14,0.18
226,ZUIAN,Top Esports,Top,31,58%,37%,118,98,176,3.0,...,669,23.2%,19.6%,8518.0,274,21.0%,NaN,0.41,0.12,0.15

In [31]:
worlds_player = player.where(player['Team'].isin(worlds_team))
worlds_player.dropna(inplace = True, how = 'all')
worlds_player

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,DPM,DMG%,D%P15,TDPG,EGPM,GOLD%,STL,WPM,CWPM,WCPM
1,Canyon,Gen.G,Jungle,11.0,82%,36%,35.0,25.0,106.0,5.6,...,395.0,15.0%,16.4%,2292.0,277.0,19.3%,2.0,0.48,0.36,0.47
2,Career,Dplus Kia,Support,16.0,44%,50%,11.0,46.0,162.0,3.8,...,197.0,8.0%,5.9%,1218.0,134.0,10.4%,0.0,1.95,0.75,0.47
3,Chovy,Gen.G,Middle,11.0,82%,45%,54.0,18.0,77.0,7.3,...,637.0,23.8%,23.7%,10648.0,332.0,23.0%,0.0,0.42,0.11,0.39
6,Delight,Hanwha Life Esports,Support,17.0,47%,35%,8.0,62.0,182.0,3.1,...,194.0,7.8%,5.9%,680.0,138.0,10.6%,0.0,2.17,0.82,0.55
7,Doran,T1,Top,18.0,50%,39%,47.0,48.0,91.0,2.9,...,551.0,20.0%,18.1%,8693.0,257.0,19.9%,0.0,0.43,0.17,0.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,Wei,Invictus Gaming,Jungle,15.0,60%,60%,61.0,44.0,144.0,4.7,...,485.0,15.1%,15.8%,4256.0,272.0,20.6%,NaN,0.46,0.34,0.42
215,Wenbo,Bilibili Gaming,Top,20.0,70%,45%,61.0,54.0,122.0,3.4,...,601.0,20.7%,20.3%,10206.0,266.0,19.0%,NaN,0.33,0.15,0.15
221,Xun,Bilibili Gaming,Jungle,35.0,71%,53%,140.0,98.0,341.0,4.9,...,483.0,16.9%,18.8%,3356.0,284.0,20.3%,NaN,0.39,0.27,0.31
224,Zhuo,Top Esports,Support,31.0,58%,60%,27.0,104.0,349.0,3.6,...,196.0,6.7%,6.0%,898.0,138.0,10.6%,NaN,2.03,0.50,0.46
226,ZUIAN,Top Esports,Top,31.0,58%,37%,118.0,98.0,176.0,3.0,...,669.0,23.2%,19.6%,8518.0,274.0,21.0%,NaN,0.41,0.12,0.15

### Làm sạch và tiền xử lý dữ liệu

In [32]:
worlds_player['FB%'] = worlds_player['FB%'].apply(convert_percentage_to_float)
worlds_player.rename(columns={'FB%': 'First Blood Rate'}, inplace=True)

In [47]:
worlds_player['First Blood'] = worlds_player['First Blood Rate'] * worlds_player['GP']
worlds_player['First Blood'] = worlds_player['First Blood'].apply(lambda x: round(x) if not pd.isnull(x) else 0)
worlds_player

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,DMG%,D%P15,TDPG,EGPM,GOLD%,STL,WPM,CWPM,WCPM,First Blood
1,Canyon,Gen.G,Jungle,11.0,82%,36%,35.0,25.0,106.0,5.6,...,15.0%,16.4%,2292.0,277.0,19.3%,2.0,0.48,0.36,0.47,2
2,Career,Dplus Kia,Support,16.0,44%,50%,11.0,46.0,162.0,3.8,...,8.0%,5.9%,1218.0,134.0,10.4%,0.0,1.95,0.75,0.47,7
3,Chovy,Gen.G,Middle,11.0,82%,45%,54.0,18.0,77.0,7.3,...,23.8%,23.7%,10648.0,332.0,23.0%,0.0,0.42,0.11,0.39,0
6,Delight,Hanwha Life Esports,Support,17.0,47%,35%,8.0,62.0,182.0,3.1,...,7.8%,5.9%,680.0,138.0,10.6%,0.0,2.17,0.82,0.55,5
7,Doran,T1,Top,18.0,50%,39%,47.0,48.0,91.0,2.9,...,20.0%,18.1%,8693.0,257.0,19.9%,0.0,0.43,0.17,0.19,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,Wei,Invictus Gaming,Jungle,15.0,60%,60%,61.0,44.0,144.0,4.7,...,15.1%,15.8%,4256.0,272.0,20.6%,NaN,0.46,0.34,0.42,5
215,Wenbo,Bilibili Gaming,Top,20.0,70%,45%,61.0,54.0,122.0,3.4,...,20.7%,20.3%,10206.0,266.0,19.0%,NaN,0.33,0.15,0.15,2
221,Xun,Bilibili Gaming,Jungle,35.0,71%,53%,140.0,98.0,341.0,4.9,...,16.9%,18.8%,3356.0,284.0,20.3%,NaN,0.39,0.27,0.31,3
224,Zhuo,Top Esports,Support,31.0,58%,60%,27.0,104.0,349.0,3.6,...,6.7%,6.0%,898.0,138.0,10.6%,NaN,2.03,0.50,0.46,7
226,ZUIAN,Top Esports,Top,31.0,58%,37%,118.0,98.0,176.0,3.0,...,23.2%,19.6%,8518.0,274.0,21.0%,NaN,0.41,0.12,0.15,3

### Tuyển thủ chuyên nghiệp nào sẽ có KDA cao nhất?

In [46]:
worlds_player_kda = worlds_player.groupby('Player').agg({'K': 'sum', 'D': 'sum', 'A': 'sum'})
worlds_player_kda['agg_KDA'] = (worlds_player_kda['K'] + worlds_player_kda['A']) / (worlds_player_kda['D'] + 1)  # Adding 1 to avoid division by zero
worlds_player_kda.sort_values(by='agg_KDA', ascending=False)

                K      D      A   agg_KDA
Player
Knight      260.0  105.0  315.0  5.424528
Rookie      145.0   76.0  246.0  5.077922
Viper       251.0  112.0  322.0  5.070796
Duro         16.0   67.0  324.0  5.000000
Hope        236.0  111.0  324.0  5.000000
Ruler       132.0   59.0  168.0  5.000000
Tarzan      197.0  127.0  440.0  4.976562
Zeka        161.0   81.0  245.0  4.951220
Xun         170.0  125.0  443.0  4.865079
Chovy       108.0   59.0  180.0  4.800000
Keria        26.0   86.0  389.0  4.770115
Kael         32.0  138.0  608.0  4.604317
Bluffing      2.0    6.0   30.0  4.571429
Canyon       75.0   65.0  225.0  4.545455
Flandre      26.0   20.0   68.0  4.476190
Smash       158.0   72.0  167.0  4.452055
Meiko        32.0  105.0  434.0  4.396226
Assum        52.0   28.0   74.0  4.344828
Wei         134.0  104.0  311.0  4.238095
Shanks      217.0  135.0  338.0  4.080882
Peyz        206.0   98.0  188.0  3.979798
Zhuo         31.0  125.0  462.0  3.912698
ShowMaker   125.0   82.0  190.0  3.795181
ON           46.0  169.0  598.0  3.788235
Breathe     168.0  119.0  275.0  3.691667
JiaQi       136.0   77.0  143.0  3.576923
Creme       152.0  117.0  267.0  3.550847
Career       20.0  105.0  347.0  3.462264
Delight      18.0  118.0  389.0  3.420168
Wenbo        61.0   54.0  122.0  3.327273
JackeyLove  190.0  135.0  260.0  3.308824
Kiin        103.0   77.0  155.0  3.307692
Tian        143.0  145.0  326.0  3.212329
Gumayusi    145.0  116.0  230.0  3.205128
Lucid        84.0  105.0  248.0  3.132075
Bin          48.0   41.0   82.0  3.095238
Zeus        122.0  117.0  211.0  2.822034
Faker        99.0  112.0  219.0  2.814159
Oner         92.0  114.0  227.0  2.773913
ZUIAN       148.0  135.0  225.0  2.742647
Painter       6.0    9.0   21.0  2.700000
Doran       101.0  104.0  172.0  2.600000
TheShy       97.0  104.0  172.0  2.561905
Kanavi      115.0  166.0  292.0  2.437126
Siwoo        82.0  110.0  131.0  1.918919

### Tuyển thủ nào sẽ có trung bình sát thương trong một trận đấu cao nhất?

In [51]:
worlds_player.sort_values(by='DPM', ascending=False)[['Player', 'Team', 'DPM']]
# JiaQi is in a weaker team, so he might be farming Nirvana group opponents.

         Player                 Team    DPM
182       JiaQi      Invictus Gaming  930.0
159       Assum      Invictus Gaming  897.0
202      Rookie      Invictus Gaming  858.0
212       Viper      Bilibili Gaming  842.0
181  JackeyLove          Top Esports  839.0
..          ...                  ...    ...
106      Career            Dplus Kia  195.0
6       Delight  Hanwha Life Esports  194.0
8          Duro                Gen.G  184.0
112     Delight  Hanwha Life Esports  180.0
117        Duro                Gen.G  167.0

[85 rows x 3 columns]

### Tuyển thủ chuyên nghiệp nào sẽ có số mạng tham gia hạ gục trung bình cao nhất?

In [53]:
worlds_player.sort_values(by='KP', ascending=False)[['Player', 'Team', 'KP']]

      Player             Team     KP
15     Keria               T1  84.4%
79      Zhuo      Top Esports  81.8%
2     Career        Dplus Kia  81.2%
62        ON  Bilibili Gaming  80.7%
117     Duro            Gen.G  80.4%
..       ...              ...    ...
215    Wenbo  Bilibili Gaming  46.3%
70    TheShy  Invictus Gaming  46.0%
172  Flandre  Bilibili Gaming  45.4%
209   TheShy  Invictus Gaming  44.1%
24     Siwoo        Dplus Kia  41.3%

[85 rows x 3 columns]